#!/usr/bin/env bash
# Script to configure nginx for load balancer
sudo apt-get -y update
sudo apt-get install -y nginx
HOSTNAME=$(hostname)
sudo sed -i "/location \/ {/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default
sudo service nginx restart