#!/usr/bin/env bash
# Script to setup HAproxy
sudo apt-get update
sudo apt-get install haproxy -t trusty-backports
sudo service haproxy start
sudo echo $'frontend http-in\n\tbind *:80\n\tdefault_backend servers' | sudo tee -a /etc/haproxy/haproxy.cfg
sudo echo $'backend servers\n\tbalance roundrobin\n\tserver 321-web-01 35.231.20.106\n\tserver 321-web-02 35.229.86.150' | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart