#!/usr/bin/env bash
# Script print 1-20 with regional bad luck numbers; use case
i=1
while [ $i -le 20 ]
do
case $i in
4)
echo "bad luck"
;;
9)
echo "bad luck"
;;
17)
echo "bad luck"
;;
*)
echo "Holberton School"
;;
esac
(( i++ ))
done
exit 0
