#!/usr/bin/env bash
# Script print 1-20 with regional bad luck numbers; use case
i=1
while [ $i -le 20 ]
do
case $i in
4)
echo "bad luck from China"
echo "$i"
;;
9)
echo "bad luck from Japan"
echo "$i"
;;
17)
echo "bad luck from Italy"
echo "$i"
;;
*)
echo "$i"
;;
esac
(( i++ ))
done
exit 0
