#!/usr/bin/env bash
# Script to configure nginx
sudo apt-get -y update
sudo apt-get install -y nginx
sudo chmod u+x /usr/share/nginx/html/index.html
echo "Holberton School for the win!" | sudo tee /usr/share/nginx/html/index.html
service nginx restart
