#!/usr/bin/env bash
# Script to configure nginx + 404 error
sudo apt-get -y update
sudo apt-get install -y nginx
sudo chmod u+x /usr/share/nginx/html/index.html
echo "Holberton School for the win!" | sudo tee /usr/share/nginx/html/index.html
sudo sed -i '26 i \     rewrite ^/redirect_me www.amazon.com permanent;' /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/404.html
sudo sed -i "s/#error_page 404 \/404.html;/error_page 404 \/404.html;/" /etc/nginx/sites-available/default
sudo service nginx restart
