#!/usr/bin/env bash
#Script run Nginx as user 'nginx'
pkill -f apache2
sudo chown nginx:nginx /etc/nginx/nginx.conf
sudo chmod 700 /etc/nginx/nginx.conf
sudo sed -i "s/80 default/8080 default/" /etc/nginx/sites-enabled/default
sudo -u nginx service nginx start